# Generated by Django 3.0.5 on 2020-08-14 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SubLessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64)),
                ('lesson_name', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('webUpdate', models.BooleanField()),
                ('mobUpdate', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoLessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64)),
                ('lesson_name', models.CharField(max_length=64)),
                ('sublesson_name', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=128, unique=True)),
                ('chanel', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
