# Generated by Django 3.0.5 on 2020-08-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolessons',
            name='isVideo',
            field=models.BooleanField(default=True),
        ),
    ]
