# Generated by Django 3.0.5 on 2020-08-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20200815_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublessons',
            name='mobUpdate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sublessons',
            name='webUpdate',
            field=models.BooleanField(default=True),
        ),
    ]
