# Generated by Django 3.0.5 on 2020-08-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20200815_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolessons',
            name='emb_url',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='videolessons',
            name='url',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
