# Generated by Django 3.0.5 on 2020-08-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20200815_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=128)),
                ('lesson_name', models.CharField(max_length=128)),
                ('sublesson_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='lessons',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='project_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='sublessons',
            name='lesson_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='sublessons',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='sublessons',
            name='project_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='videolessons',
            name='chanel',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='videolessons',
            name='lesson_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='videolessons',
            name='project_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='videolessons',
            name='sublesson_name',
            field=models.CharField(max_length=128),
        ),
    ]
