# Generated by Django 3.0.5 on 2020-08-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20200815_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed',
            name='sublesson_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='videolessons',
            name='sublesson_name',
            field=models.CharField(max_length=256),
        ),
    ]
