# Generated by Django 3.0.5 on 2020-08-15 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20200815_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
