# Generated by Django 3.0.5 on 2020-08-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed',
            name='isChecked',
            field=models.BooleanField(default=False),
        ),
    ]
